name: Build Pull Request
on:
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: "npm"
         
    - run: npm ci
    - run: npm run prepublishOnly
    - run: npm run test:update
    - run: npm run test