name: Deploy to NPM
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: "npm"
        
     
    - run: npm ci
    - run: npm run prepublishOnly
    - run: npm run test:update
    - run: npm run test
    
    - name: "Automated Version Bump"
      id: version-bump
      uses: "phips28/gh-action-bump-version@master"
      with:
        tag-prefix: ''
        skip-tag: true
        skip-push: true
        skip-commit: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push files and tag
      uses: Amraneze/push-to-protected-branch@v1.5.0
      with:
        repository: ${{ github.repository }}
        branch_name: ${{ github.ref_name }}
        github_token: ${{ secrets.BOT_PAT_TOKEN }}
        commit_message: 'CI: build version ${{ steps.version-bump.outputs.newTag }} [actions skip]'
        tag_version: ${{ steps.version-bump.outputs.newTag }}
        files_to_commit: 'package.json'
        create_tag: true

    - name:  'Output Step'
      env:
        NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
      run: echo "new tag $NEW_TAG"

    - name: "Publish to NPM"
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}

    
